package.json
pages/mainPages/Home.jsx
pages/mainPages/NotFound.jsx
pages/mainPages/Performance.jsx
pages/mainPages/PerformanceDetail.jsx
pages/subPages/BookSystem.jsx
pages/subPages/Login.jsx
pages/subPages/MyOrder.jsx
pages/subPages/MyPages.jsx
pages/subPages/Support.jsx
src/components/api/firebase.js
yarn.lock

파이어베이스 기반 로그인 컴포넌트 완성했습니다. 
develop branch로 merge하려 합니다. 보고 문제가 없을 시 동의해주세요~

FEAT Create login components with firebase

---

pages/api/auth/firebase.js
pages/subPages/Login.jsx
src/components/atoms/AvatarImage.jsx

기존 아이디 패스워드 인증과 회원가입 유효성 검사 인증 구현 완료 했습니다. develop 브렌치로 merge 요청합니다.
closed #5

FEAT:Authenticate sign-in and sign-up with firebase

---

global.js
pages/mainPages/Performance.jsx
src/components/molecules/Navbar.jsx

global.js 전역 스타일 및 Navbar 스타일 변경했습니다.

STYLE: global.js 전역 스타일 및 Navbar 스타일 변경

---

src/components/atoms/Loading.jsx
src/components/molecules/Layout.jsx

Loading 컴포넌트 생성, 스타일링 완료!!!
closes #13

 Loading 컴포넌트

---

package.json
src/components/molecules/Navbar.jsx
yarn.lock

navbar list에 isActive 클래스 추가할 때 코드 중복으로 map 활용해 가독성 향상
closes #16

REFACTOR: Navbar

---

src/components/molecules/Navbar.jsx

toggle 기능 추가 및 dropdown 영역 밖 클릭 시 dropdown 영역 사라지도록 구현
closes #15

FEAT: Navbar dropdown 

---

pages/subPages/MyPages.jsx
src/components/molecules/Layout.jsx

avatar image에 hover하면 이미지 변경하는 div가 떠야 하는데 안 떠서 수정했습니다.

STYLE: Mypage avatar Style 변경

---

package.json
pages/_app.js
pages/mainPages/BestPerformence.jsx
pages/mainPages/NewPerformance.jsx
src/components/molecules/HomeNavbar.jsx
src/components/molecules/ImageSlider.jsx
src/components/molecules/Layout.jsx
src/components/molecules/Navbar.jsx
yarn.lock

전체적으로 문서 수정(Navbar, Layout, app, HomeNavbar)

DOC: 전체적으로 문서 수정(Navbar, Layout, app, HomeNavbar)

---

pages/_app.js
pages/index.js
pages/subPages/MyPages.jsx
src/components/molecules/Layout.jsx
src/components/molecules/Navbar.jsx

dropdown 클릭 시 dropdown menu 사라지지 않는 것 해결

FEAT: dropdown 

---

pages/api/auth/firebase.js
pages/subPages/Login.jsx
pages/subPages/Register.jsx
src/components/atoms/AvatarImage.jsx
src/components/molecules/Navbar.jsx

레지스터 컴포넌트 회원 가입기능 개발했습니다.
closed #12

FEAT: Sign-up with firebase in Register Component

---

pages/subPages/Login.jsx
pages/subPages/Register.jsx

change In-line styling to Variable-styling
closed #28

STYLE: Register Component

---

pages/subPages/Login.jsx
pages/subPages/NotifyLogin.jsx
pages/subPages/Register.jsx
src/components/atoms/AvatarImage.jsx

FEAT: Communicate user information and relative method to Navbar 
closed #31

FEAT: Communicate user information and relative method to Navbar

---

pages/mainPages/Home.jsx
pages/subPages/Register.jsx

FEAT: Add Auth form in Register when signed
closed #33

FEAT: Add Auth form in Register when signed

---

pages/description/[performenceid].js

수정함: FEAT/ Add to description in Mainpages
#35 close

수정함: FEAT/ Add to description in Mainpages

---

pages/subPages/Login.jsx
pages/subPages/Register.jsx

STYLE: Register form for newAccount 완료
closed #39

STYLE: Register form for newAccount

---

pages/_app.js
pages/description/[performenceid].js
pages/index.js
pages/mainPages/Performance.jsx
pages/mainPages/PerformanceDetail.jsx
src/components/molecules/Card.jsx
src/components/molecules/ImageSlider.jsx
src/components/molecules/Layout.jsx
src/components/molecules/PerformanceList.jsx
src/components/molecules/RecommendPerformance.jsx
src/localServer.js
src/serverRouter/totalPerformanceRouter.js

전체 공연 페이지 api 요청 및 대략적인 스타일링 했습니다.
closes #41

Feature main pages/performance

---

pages/description/[performenceid].js
pages/index.js
pages/mainPages/Performance.jsx
src/components/atoms/Loading.jsx
src/components/molecules/PerformanceList.jsx

로딩 컴포넌트 생성 및 filtering 리팩토링(1)
closes #51

Feature loading/styling

---

pages/api/auth/firebase.js
pages/subPages/Login.jsx
pages/subPages/MyPages.jsx
pages/subPages/Register.jsx

STYLE: Mypage component for Adding auth with firebase
closed #54

STYLE: Mypage component

---

pages/404.jsx
pages/mainPages/NotFound.jsx

FEAT: create error custom page
closed #58

FEAT: create error custom page

---

pages/404.jsx
pages/mainPages/Support.jsx
pages/subPages/Support.jsx

고객센터 페이지, 기본적인 UI와 스타일링 작업했습니다.
closed #60

FEAT: Support Component

---

pages/404.jsx
pages/mainPages/Support.jsx
pages/subPages/ComingSoon.jsx

고객센터 - 예매 관련 문의 - Coming Soon
closed #62

FEAT: Coming-Soon UI

---

pages/api/auth/firebase-database.js
pages/api/auth/firebase.js
pages/subPages/Login.jsx
pages/subPages/MyPages.jsx
pages/subPages/Register.jsx
pages/subPages/SupportInquery.jsx
src/components/Recoil/recoil-auth.js

FEAT: Add database with firebaseStore
closed #66

FEAT: Add database with firebaseStore

---

pages/description/[performenceid].js
pages/subPages/HelpInquiry.jsx
src/components/molecules/Navbar.jsx
src/components/molecules/PerformanceList.jsx
src/components/molecules/ReservationItem.jsx
src/components/organisms/SupportChat.jsx
src/contexts/resetStyled.js

STYLE: HelpInquiry and SupportChat Components
closed #81

STYLE: HelpInquiry and SupportChat Components

---

pages/mainPages/Support.jsx
pages/subPages/HelpInquiry.jsx
pages/subPages/MyPages.jsx
src/components/molecules/Navbar.jsx
src/components/organisms/SupportChat.jsx

FEAT: Provide some information in userData with SupportChat
closed #83

FEAT: Provide some information in userData with SupportChat

---

pages/mainPages/Support.jsx
pages/subPages/HelpInquiry.jsx
src/components/organisms/SupportChat.jsx

STYLE: Edit-SupportChat

---

next.config.js
pages/mainPages/test.jsx
src/localServer2.js
src/serverRouter/mainImageRouter.js

FIX: edit for openAPI / create proxy

---

pages/subPages/Login.jsx
src/components/molecules/Layout.jsx
src/components/molecules/Navbar.jsx

FEAT: user-states are notified with react-hot-toast
closed #93

FEAT: user-states are notified with react-hot-toast

---

pages/index.js
src/components/atoms/BookmarkHeart.jsx
src/components/molecules/Navbar.jsx
src/components/molecules/PerformanceList.jsx

STYLE: BookmarkHeart

---

pages/index.js
pages/subPages/HelpInquiry.jsx
src/components/molecules/Navbar.jsx
src/components/organisms/SupportChat.jsx

FIX-DOCS: resolve typeError and router path redirecting
closed #105

FIX-DOCS: resolve typeError and router path redirecting

---

pages/mainPages/Performance.jsx

STYLE: performance/form
closed #110

STYLE: performance/form

---

pages/mainPages/Support.jsx
pages/subPages/Login.jsx
pages/subPages/MyPages.jsx
pages/subPages/Register.jsx
src/components/molecules/Navbar.jsx

FIX: logic error
1. 회원 가입 직후, 마이페이지 접속 할 때 일시적으로 undefined가 발생하는 이슈 해결
2. input value uncontrolled 이슈 해결

FIX: logic error

---

pages/subPages/Bookmark.jsx
src/components/atoms/BookmarkHeart.jsx
src/components/molecules/PerformanceList.jsx
src/modules/bookmarkModules.js

state 이용해서 Bookmark 재구현했습니다.
closes #117

Feature book mark with state

---

.gitignore
README.md
package.json

set env server

---

package.json
pages/mainPages/Performance.jsx
yarn.lock

* react-date-range 에서 react-datepick 라이브러리로 캘린더 수정
* 선택날짜부터 이후 공연까지 검색하여 리스트화 기능 추가

FEAT: make a calender and add library react-datepick

---

.github/workflows/firebase-hosting-merge.yml
.github/workflows/firebase-hosting-pull-request.yml
.github/workflows/firebase-testing.yml
package.json
pages/mainPages/Performance.jsx
src/store/server/getAPI/useGetPerformance.js
yarn.lock

Feature performance/date picker
"FIX: locale object was not found in string ['ko']"

Feature performance/date picker

---

README.md

DOC readMe/added cell of state management

DOC readMe/added cell of state management
